"""add last fetch for artist and hidden for release

Revision ID: 2e7d5dc69f0a
Revises: 4f450ebd2793
Create Date: 2026-02-18 23:03:08.565807

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2e7d5dc69f0a'
down_revision: str | Sequence[str] | None = '4f450ebd2793'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('last_fetch', sa.DateTime(), nullable=True))
    op.add_column('releases', sa.Column('hidden', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'hidden')
    op.drop_column('artists', 'last_fetch')
    # ### end Alembic commands ###
