"""add user settings

Revision ID: 4f450ebd2793
Revises: 5925ebf1815b
Create Date: 2026-02-16 11:00:57.874777

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4f450ebd2793'
down_revision: str | Sequence[str] | None = '5925ebf1815b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'app_user_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('min_scrobbles', sa.Integer(), nullable=False),
        sa.Column('releases_not_before', sa.Date(), nullable=False),
        sa.Column('id_user', sa.Integer(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.ForeignKeyConstraint(['id_user'], ['app_users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_user_settings')
    # ### end Alembic commands ###
