"""Initial schema

Revision ID: 9ce6cfa46dd2
Revises: 
Create Date: 2026-02-15 16:54:49.873570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce6cfa46dd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('lastfm_username', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_user_artists',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_artist', sa.Integer(), nullable=False),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('nb_scrobbles', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_artist'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_user', 'id_artist')
    )
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_title', sa.String(length=255), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('nb_tracks', sa.Integer(), nullable=False),
    sa.Column('id_artist', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_artist'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_user_releases',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_release', sa.Integer(), nullable=False),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('nb_scrobbles', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_release'], ['releases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_user', 'id_release')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_user_releases')
    op.drop_table('releases')
    op.drop_table('app_user_artists')
    op.drop_table('artists')
    op.drop_table('app_users')
    # ### end Alembic commands ###
